#!/usr/bin/env python3
"""Verify complete source/pin identities and regenerate reversible coupled observation bindings."""
import argparse,hashlib,json,shutil,subprocess,sys,tempfile
from pathlib import Path
sys.dont_write_bytecode=True
ROOT=Path(__file__).resolve().parents[1]
def need(ok,label):
    if not ok:raise ValueError(label)
def verify(output):
    env=json.loads((output/'environment.json').read_text());need(env['workingTreeDirty'] is False and len(env['candidate'])==40,'clean exact committed producer')
    for path,digest in env['sourceHashes'].items():need(hashlib.sha256((output/'source'/path).read_bytes()).hexdigest()==digest,'complete producer source '+path)
    protected=output/'source/Fixtures/QRReconstructionAdoption/CoupledOriginalSources.json'
    need(hashlib.sha256(protected.read_bytes()).hexdigest()=='e3f81abcef64cc84b062de2f380475b8df8eabb8e738912539bc8049b62f37be','immutable original coupled gas source identities')
    manifest=json.loads(protected.read_text());need(manifest['revision']=='b7d86c445d7aa40ed63bab1562e9c956b1c5c31e','protected original gas checkpoint')
    pins=[('original','0.1.0-alpha.16','1977b38a66382533be902350b40e7084a2d1e9ca'),('shared','0.1.0-alpha.19','00eac5537843c85c3c25a7ecef1120f49e8aa469')]
    with tempfile.TemporaryDirectory(prefix='qr-coupled-source-replay-') as scratch:
        scratch=Path(scratch);raw_root=scratch/'original-raw'
        for variant,version,revision in pins:
            binding=json.loads((output/variant/'bindings.json').read_text())
            need(binding['variant']==variant and binding['originalRevision']==manifest['revision'],'complete binding source identity')
            need(len(binding['sources'])==34 and {b['path'] for b in binding['sources']}==set(manifest['sources']),'complete actual CPU source support')
            pin=json.loads((output/variant/'Package.resolved').read_text())['pins'];need(len(pin)==1 and pin[0]['identity']=='continuumkit' and pin[0]['state']=={'version':version,'revision':revision},'exact coupled dependency pin')
            for b in binding['sources']:
                compiled=output/variant/'source/Sources/CoupledCapture'/Path(b['path']).name
                text=compiled.read_text();need(hashlib.sha256(compiled.read_bytes()).hexdigest()==b['compiledSHA256'],'actual compiled source hash')
                for patch in reversed(b['patches']):
                    need(text.count(patch['traced'])==1,'unique reversible observation');text=text.replace(patch['traced'],patch['original'])
                raw=text.encode();need(hashlib.sha256(raw).hexdigest()==b['sourceSHA256'],'restored original arithmetic bytes')
                if variant=='original':
                    item=manifest['sources'][b['path']];need(b['sourceSHA256']==item['sha256'] and hashlib.sha1(b'blob '+str(len(raw)).encode()+b'\0'+raw).hexdigest()==item['blob'],'complete protected original bytes')
                    target=raw_root/b['path'];target.parent.mkdir(parents=True,exist_ok=True);target.write_bytes(raw)
                else:need(raw==(output/'source'/b['path']).read_bytes(),'exact shared producer arithmetic')
            rebuilt=scratch/variant
            subprocess.run([sys.executable,str(output/'source/Scripts/prepare-qr-coupled-capture.py'),'--variant',variant,'--output',str(rebuilt),'--original-source-root',str(raw_root)],check=True,stdout=subprocess.DEVNULL)
            need(json.loads((rebuilt/'bindings.json').read_text())==binding,'regenerated trusted passive observation recipe')
            for file in (rebuilt/'Sources/CoupledCapture').iterdir():need(file.read_bytes()==(output/variant/'source/Sources/CoupledCapture'/file.name).read_bytes(),'complete regenerated compiled fixture/source '+file.name)
            need((rebuilt/'Package.swift').read_bytes()==(output/variant/'source/Package.swift').read_bytes(),'regenerated exact consumer manifest')
            need(not any('/'+name+'.framework/' in (output/variant/'linkage.txt').read_text() for name in ['Metal','MetalKit','AppKit','SwiftUI']),'CPU-only coupled study capture')
    return {'schemaVersion':1,'status':'passed','candidate':env['candidate'],'completeProductionSources':34,'scope':'exact original/shared complete CPU source, immutable dependencies and regenerated byte-reversible observations'}
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('output',type=Path);a=p.parse_args();d=verify(a.output)
    (a.output/'source-verification.json').write_text(json.dumps(d,indent=2,sort_keys=True)+'\n');print('PASS complete coupled source bindings and frozen dependency identities')
