import AVFoundation
import Foundation

/// A dry (ideally anechoic) mono recording to play through a room.
public struct DryClip: Equatable, Sendable, Identifiable {
    public var id: String
    public var name: String
    /// Source, author and licence, shown wherever the clip is offered.
    public var credit: String
    public var samples: [Float]
    public var sampleRate: Int

    /// Clips are scaled to this peak so they play at similar levels.
    public static let peak: Float = 0.5
    /// Longer files are cut to this many seconds.
    public static let maximumDuration = 60.0

    public init(id: String, name: String, credit: String, samples: [Float], sampleRate: Int) {
        self.id = id
        self.name = name
        self.credit = credit
        self.samples = Self.normalized(samples)
        self.sampleRate = sampleRate
    }

    public var duration: Double { Double(samples.count) / Double(sampleRate) }

    static func normalized(_ samples: [Float]) -> [Float] {
        let largest = samples.reduce(Float(0)) { max($0, abs($1)) }
        guard largest > 0 else { return samples }
        return samples.map { $0 * peak / largest }
    }
}

// MARK: - Test signals

extension DryClip {
    /// Half a second of pink noise and then silence: the classic way to hear a decay.
    public static func noiseBurst(sampleRate: Int) -> DryClip {
        var random = SplitMix(seed: 1)
        let burst = Int(0.5 * Double(sampleRate))
        let ramp = Int(0.005 * Double(sampleRate))
        // Paul Kellet's economy pink-noise filter.
        var (b0, b1, b2) = (0.0, 0.0, 0.0)
        var samples = [Float](repeating: 0, count: burst + 2 * sampleRate)
        for i in 0..<burst {
            let white = random.nextSigned()
            b0 = 0.99765 * b0 + white * 0.0990460
            b1 = 0.96300 * b1 + white * 0.2965164
            b2 = 0.57000 * b2 + white * 1.0526913
            let edge = min(1, Double(min(i, burst - 1 - i)) / Double(ramp))
            samples[i] = Float((b0 + b1 + b2 + white * 0.1848) * edge)
        }
        return DryClip(
            id: "noise-burst", name: "Noise burst", credit: "Generated by RoomCAD", samples: samples,
            sampleRate: sampleRate)
    }

    /// Single clicks a second apart: each shows the early reflections and the decay.
    public static func clicks(sampleRate: Int) -> DryClip {
        var samples = [Float](repeating: 0, count: 4 * sampleRate)
        for second in 0..<3 {
            // A two-sample click keeps the spectrum broad without being harsh.
            samples[second * sampleRate + sampleRate / 10] = 1
            samples[second * sampleRate + sampleRate / 10 + 1] = -0.5
        }
        return DryClip(
            id: "clicks", name: "Clicks", credit: "Generated by RoomCAD", samples: samples,
            sampleRate: sampleRate)
    }
}

/// Deterministic generator so test signals are identical on every run.
struct SplitMix {
    var state: UInt64

    init(seed: UInt64) { state = seed }

    mutating func next() -> UInt64 {
        state &+= 0x9E37_79B9_7F4A_7C15
        var z = state
        z = (z ^ (z >> 30)) &* 0xBF58_476D_1CE4_E5B9
        z = (z ^ (z >> 27)) &* 0x94D0_49BB_1331_11EB
        return z ^ (z >> 31)
    }

    /// Uniform in [-1, 1).
    mutating func nextSigned() -> Double {
        Double(next() >> 11) / Double(1 << 52) - 1
    }
}

// MARK: - Files

public enum DryClipError: LocalizedError {
    case unreadable(String)

    public var errorDescription: String? {
        switch self {
        case .unreadable(let message): message
        }
    }
}

extension DryClip {
    /// Reads any audio file Core Audio can decode, mixes it to mono and converts it to `sampleRate`.
    /// Files longer than `maximumDuration` are cut.
    public static func load(
        contentsOf url: URL, sampleRate: Int, id: String? = nil, name: String? = nil,
        credit: String = "Your file"
    ) throws -> DryClip {
        let file: AVAudioFile
        do {
            file = try AVAudioFile(forReading: url)
        } catch {
            throw DryClipError.unreadable("\(url.lastPathComponent) is not an audio file RoomCAD can read.")
        }
        let format = file.processingFormat
        let frames = AVAudioFrameCount(min(Double(file.length), maximumDuration * format.sampleRate))
        guard frames > 0, let buffer = AVAudioPCMBuffer(pcmFormat: format, frameCapacity: frames) else {
            throw DryClipError.unreadable("\(url.lastPathComponent) contains no audio.")
        }
        try file.read(into: buffer, frameCount: frames)
        guard let channels = buffer.floatChannelData else {
            throw DryClipError.unreadable("\(url.lastPathComponent) could not be decoded to floating point.")
        }
        let count = Int(buffer.frameLength)
        let channelCount = Int(format.channelCount)
        var mono = [Float](repeating: 0, count: count)
        for c in 0..<channelCount {
            for i in 0..<count { mono[i] += channels[c][i] / Float(channelCount) }
        }
        let converted = try resample(mono, from: format.sampleRate, to: Double(sampleRate))
        return DryClip(
            id: id ?? url.absoluteString, name: name ?? url.deletingPathExtension().lastPathComponent,
            credit: credit, samples: converted, sampleRate: sampleRate)
    }

    /// Band-limited sample-rate conversion by Core Audio.
    static func resample(_ samples: [Float], from source: Double, to target: Double) throws -> [Float] {
        guard source != target else { return samples }
        guard let input = AVAudioFormat(standardFormatWithSampleRate: source, channels: 1),
            let output = AVAudioFormat(standardFormatWithSampleRate: target, channels: 1),
            let converter = AVAudioConverter(from: input, to: output),
            let inBuffer = AVAudioPCMBuffer(
                pcmFormat: input, frameCapacity: AVAudioFrameCount(samples.count)),
            let outBuffer = AVAudioPCMBuffer(
                pcmFormat: output,
                frameCapacity: AVAudioFrameCount(Double(samples.count) * target / source) + 1024)
        else { throw DryClipError.unreadable("Could not convert the sample rate.") }
        converter.sampleRateConverterQuality = AVAudioQuality.max.rawValue
        inBuffer.frameLength = inBuffer.frameCapacity
        samples.withUnsafeBufferPointer {
            inBuffer.floatChannelData![0].update(from: $0.baseAddress!, count: $0.count)
        }
        nonisolated(unsafe) var supplied = false
        nonisolated(unsafe) let source = inBuffer
        var error: NSError?
        let status = converter.convert(to: outBuffer, error: &error) { _, inputStatus in
            if supplied {
                inputStatus.pointee = .endOfStream
                return nil
            }
            supplied = true
            inputStatus.pointee = .haveData
            return source
        }
        guard status != .error else {
            throw DryClipError.unreadable(
                "Could not convert the sample rate: \(error?.localizedDescription ?? "").")
        }
        return Array(
            UnsafeBufferPointer(start: outBuffer.floatChannelData![0], count: Int(outBuffer.frameLength)))
    }
}

// MARK: - Bundled recordings

extension DryClip {
    struct Entry: Codable {
        var id: String
        var name: String
        var file: String
        var credit: String
    }

    /// The recordings shipped with RoomCAD, listed in `Clips/clips.json`, at `sampleRate`.
    public static func bundled(sampleRate: Int) -> [DryClip] {
        guard let folder = Bundle.module.url(forResource: "Clips", withExtension: nil),
            let data = try? Data(contentsOf: folder.appendingPathComponent("clips.json")),
            let entries = try? JSONDecoder().decode([Entry].self, from: data)
        else { return [] }
        return entries.compactMap { entry in
            try? load(
                contentsOf: folder.appendingPathComponent(entry.file), sampleRate: sampleRate, id: entry.id,
                name: entry.name, credit: entry.credit)
        }
    }

    /// Bundled recordings followed by the generated test signals.
    public static func library(sampleRate: Int) -> [DryClip] {
        bundled(sampleRate: sampleRate) + [
            noiseBurst(sampleRate: sampleRate), clicks(sampleRate: sampleRate),
        ]
    }
}
